name: ci

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    name: ${{ matrix.tox-env }}
    strategy:
      matrix:
        include:
          - python-version: 3.8
            tox-env: py38-codelint  
          - python-version: 3.5
            tox-env: py35-codetest-noorgs
          - python-version: 3.5
            tox-env: py35-codetest-withorgs
          - python-version: 3.8
            tox-env: py38-codetest-noorgs
          - python-version: 3.8
            tox-env: py38-codetest-withorgs
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: pip install tox
      - name: Test with tox
        run: tox -e ${{ matrix.tox-env }}
