name: ci

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test-python35:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tox-env-suffix:
          - codetest-noorgs
          - codetest-withorgs
          - codelint
        python-version:
          - 3.5
          - 3.8
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: pip install tox
      - name: Test with tox
        run: tox -e ${{ matrix.python-version == '3.5' && 'py35' || 'py38' }}-${{ matrix.tox-env-suffix }}
        if: ${{ matrix.python-version == '3.5' && 'py35' || 'py38' }}-${{ matrix.tox-env-suffix }} != "codelint-py35"
